//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_DeshBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Information
    {
        public byte CompanyID { get; set; }
        public string CompName { get; set; }
        public string CompAdd { get; set; }
        public string CompTIN { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string Email { get; set; }
        public string WebAdd { get; set; }
        public string ImageLocation { get; set; }
        public string ServerName { get; set; }
        public string DBName { get; set; }
        public string DBPrefix { get; set; }
        public string ReportPath { get; set; }
        public string ComShortName { get; set; }
        public byte Sign { get; set; }
    }
}
