//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_DeshBoard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Web_InventoryEntities : DbContext
    {
        public Web_InventoryEntities()
            : base("name=Web_InventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Company_Information> Company_Information { get; set; }
        public DbSet<Iteam_Information> Iteam_Information { get; set; }
        public DbSet<new_Supplier_Name> new_Supplier_Name { get; set; }
        public DbSet<Sell_Iteam_Main> Sell_Iteam_Main { get; set; }
        public DbSet<Sell_Iteam_Sub> Sell_Iteam_Sub { get; set; }
        public DbSet<Sell_Iteam_Customer> Sell_Iteam_Customer { get; set; }
        public DbSet<Iteam_Order_Info> Iteam_Order_Info { get; set; }
        public DbSet<Iteam_Requiition_Info> Iteam_Requiition_Info { get; set; }
        public DbSet<new_Category_Name> new_Category_Name { get; set; }
        public DbSet<new_Country> new_Country { get; set; }
        public DbSet<new_Currency> new_Currency { get; set; }
        public DbSet<new_Customer_Name> new_Customer_Name { get; set; }
        public DbSet<new_Department> new_Department { get; set; }
        public DbSet<new_Item_Name> new_Item_Name { get; set; }
        public DbSet<new_SubCategory_Name> new_SubCategory_Name { get; set; }
        public DbSet<new_Unit_Name> new_Unit_Name { get; set; }
        public DbSet<Sys_User_Name> Sys_User_Name { get; set; }
        public DbSet<Sys_User_NameUp> Sys_User_NameUp { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tblMenu> tblMenus { get; set; }
        public DbSet<tblMenuWin> tblMenuWins { get; set; }
        public DbSet<tblMenuWinBak2> tblMenuWinBak2 { get; set; }
        public DbSet<tblRole> tblRoles { get; set; }
        public DbSet<new_ProductModel_Name> new_ProductModel_Name { get; set; }
    }
}
