//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_DeshBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iteam_Information
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public int SupplierID { get; set; }
        public int CategoryID { get; set; }
        public int ModelID { get; set; }
        public double Quantity { get; set; }
        public decimal BuyPrice { get; set; }
        public decimal TotalCostPrice { get; set; }
        public decimal SellPrice { get; set; }
        public decimal TotalSellPrice { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Invoice { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public int Sign { get; set; }
        public string PCName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
    }
}
