//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_DeshBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iteam_Requiition_Info
    {
        public int ID { get; set; }
        public string code { get; set; }
        public int SlNo { get; set; }
        public string PRNo { get; set; }
        public string ReqNo { get; set; }
        public string IteamID { get; set; }
        public string iteamCode { get; set; }
        public double RequisitionQty { get; set; }
        public string Unit { get; set; }
        public string CurrStock { get; set; }
        public Nullable<System.DateTime> RequisitionDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public int DeleteRow { get; set; }
        public string UserID { get; set; }
        public string PCName { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
    }
}
