//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_DeshBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_SubCategory_Name
    {
        public short SubcategoryID { get; set; }
        public string SubCategoryName { get; set; }
        public string SubShortName { get; set; }
        public int CategoryID { get; set; }
        public byte Sign { get; set; }
    }
}
