//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_DeshBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User_NameUp
    {
        public Nullable<short> CompID { get; set; }
        public short UserID { get; set; }
        public string UserName { get; set; }
        public string UserPWord { get; set; }
        public string EmpCode { get; set; }
        public string UserFullName { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string Menu_id { get; set; }
        public string Control_id { get; set; }
        public byte Active { get; set; }
        public byte mleft { get; set; }
        public int Role { get; set; }
    }
}
