//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_DeshBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenuWin
    {
        public Nullable<int> ID { get; set; }
        public string CompID { get; set; }
        public string Menu_Name { get; set; }
        public string Menu_Id { get; set; }
        public string Form_Name { get; set; }
        public string FrmMenu_Name { get; set; }
        public string FrmForm_Name { get; set; }
        public int YsnActive { get; set; }
    }
}
